import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const stamp=Date.now().toString(36),names=[`Host_${stamp}`,`Friend_${stamp}`];
try{
  const contexts=await Promise.all([browser.newContext(),browser.newContext()]);
  const pages=await Promise.all(contexts.map(c=>c.newPage()));
  const errors=[];pages.forEach(p=>p.on('pageerror',e=>errors.push(e.message)));
  const register=async(page,name,url)=>{
    await page.goto(url,{waitUntil:'networkidle'});
    if(await page.getByRole('button',{name:'Online',exact:true}).isVisible())await page.getByRole('button',{name:'Online',exact:true}).click();
    await page.getByRole('button',{name:'Create account',exact:true}).first().click();
    await page.getByLabel('Public username').fill(name);await page.getByLabel('Password',{exact:true}).fill('CorrectHorseBattery123!');
    await page.locator('.account-form button[type=submit], .account-form .primary').click();
    await page.locator('.account-row').waitFor();
  };
  await register(pages[0],names[0],'http://localhost:5173/');
  await pages[0].getByLabel('Player limit').selectOption('2');
  await pages[0].getByLabel('Public room').check();
  await pages[0].getByRole('button',{name:'Create room',exact:true}).click();
  await pages[0].locator('.room-heading h3').waitFor();
  const code=await pages[0].locator('.room-heading h3').textContent();
  await register(pages[1],names[1],`http://localhost:5173/?room=${code}`);
  await pages[1].getByRole('button',{name:'Join room',exact:true}).click();
  await pages[1].getByLabel('Ready to play').check();await pages[0].getByLabel('Ready to play').check();
  await pages[0].getByRole('button',{name:'Start room',exact:true}).waitFor({state:'visible'});
  await pages[0].waitForFunction(()=>!document.querySelector('.room-lobby .primary').disabled);
  await pages[0].getByRole('button',{name:'Start room',exact:true}).click();
  for(const page of pages)await page.getByRole('dialog').waitFor({state:'hidden'});
  const state=await pages[0].request.get(`http://localhost:5173/api/rooms/${code}`).then(r=>r.json());
  const active=state.room.game.current,waiting=1-active;
  await pages[active].getByRole('button',{name:'Roll dice',exact:false}).filter({visible:true}).first().click();
  await pages[waiting].waitForFunction(()=>document.querySelector('.current-player p').textContent!=='Eko Start');
  const first=await pages[0].request.get(`http://localhost:5173/api/rooms/${code}`).then(r=>r.json());
  const second=await pages[1].request.get(`http://localhost:5173/api/rooms/${code}`).then(r=>r.json());
  assert.deepEqual(first.room.game,second.room.game);
  await pages[0].reload({waitUntil:'networkidle'});await pages[0].getByRole('dialog').waitFor({state:'hidden'});
  assert.ok((await pages[0].locator('.account-button').textContent()).includes(names[0]));
  assert.equal(await pages[0].evaluate(()=>[...Object.keys(localStorage)].some(k=>/password|token/i.test(k))),false);
  const solo=await browser.newContext(),p=await solo.newPage();await p.goto('http://localhost:5173/',{waitUntil:'networkidle'});
  await p.getByRole('button',{name:'Computer',exact:true}).click();await p.getByRole('button',{name:'Start game',exact:true}).click();
  await p.waitForTimeout(2500);
  const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('naija-estates.local.v1')));
  assert.deepEqual(saved.state.G.aiPlayers,[1]);
  await p.setViewportSize({width:390,height:844});
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await p.screenshot({path:'tests/account-ai-mobile.png',fullPage:true});
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('Multiplayer checks passed: registration, room invite, readiness, synchronized moves, remembered login, no stored credentials, AI mode, mobile layout.');
}finally{await browser.close();}
