import { afterEach, describe, expect, it } from 'vitest';
import { createService } from '../server/service';
import type { AddressInfo } from 'node:net';
import { mkdtempSync, writeFileSync, unlinkSync, rmdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const services:ReturnType<typeof createService>[]=[];
const staticFixtures:string[]=[];
afterEach(async()=>{for(const service of services.splice(0))await service.close();for(const folder of staticFixtures.splice(0)){unlinkSync(join(folder,'index.html'));rmdirSync(folder);}});
async function fixture(adminUserIds:string[]=[]){
  const service=createService({database:':memory:',origin:'http://localhost:5173',adminUserIds});services.push(service);
  await new Promise<void>(resolve=>service.server.listen(0,'127.0.0.1',resolve));
  const url=`http://127.0.0.1:${(service.server.address() as AddressInfo).port}`;
  const request=async(path:string,data?:unknown,cookie='',origin='http://localhost:5173')=>{
    const response=await fetch(url+path,{method:data===undefined?'GET':'POST',headers:{cookie,origin,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]??''};
  };
  const account=async(name:string)=>{const result=await request('/api/register',{username:name,password:'CorrectHorseBattery123!'});expect(result.status).toBe(200);return result;};
  return {service,request,account};
}
describe('secure accounts and authoritative rooms',()=>{
  it('restricts administrator monitoring and never exposes credentials or session tokens',async()=>{
    const {service,request,account}=await fixture(['admin-test']);
    expect((await request('/api/administrator')).status).toBe(401);
    const user=await account('Operator');
    expect((await request('/api/administrator',undefined,user.cookie)).status).toBe(403);
    const row=(await service.db.prepare('SELECT * FROM users WHERE username=?').get('Operator'))!;
    await service.db.prepare('INSERT INTO users(id,username,key,salt,password) VALUES (?,?,?,?,?)').run('admin-test','Admin','admin',row.salt,row.password);
    await service.db.prepare('UPDATE sessions SET "user"=? WHERE "user"=?').run('admin-test',row.id);
    await request('/api/rooms',{cap:2,public:false},user.cookie);
    const result=await request('/api/administrator',undefined,user.cookie);
    expect(result.status).toBe(200);expect(result.body.rooms).toHaveLength(1);expect(result.body.sessionCount).toBe(1);
    const raw=JSON.stringify(result.body);expect(raw).not.toContain(row.password);expect(raw).not.toContain(row.salt);expect(raw).not.toContain('token');expect(raw).not.toContain('community');
    const normal=await account('NormalUser');
    expect((await request('/api/administrator/create',{username:'Intruder',password:'Abc123!?'},normal.cookie)).status).toBe(403);
    expect((await request('/api/administrator/delete',{id:'admin-test',confirm:'Admin'},normal.cookie)).status).toBe(403);
    const created=await request('/api/administrator/create',{username:'SecondAdmin',password:'Abc123!?'},user.cookie);
    expect(created.status).toBe(201);
    const signedIn=await request('/api/login',{username:'SecondAdmin',password:'Abc123!?'});
    expect((await request('/api/administrator',undefined,signedIn.cookie)).status).toBe(200);
    expect((await request('/api/administrator/delete',{id:created.body.user.id,confirm:'SecondAdmin'},signedIn.cookie)).status).toBe(400);
    expect((await request('/api/administrator/delete',{id:created.body.user.id,confirm:'wrong'},user.cookie)).status).toBe(400);
    expect((await request('/api/administrator/delete',{id:created.body.user.id,confirm:'SecondAdmin'},user.cookie)).status).toBe(200);
    expect((await request('/api/me',undefined,signedIn.cookie)).body.user).toBeNull();
    expect((await request('/api/administrator/edit',{id:normal.body.user.id,username:'RenamedUser'},normal.cookie)).status).toBe(403);
    expect((await request('/api/administrator/edit',{id:normal.body.user.id,username:'Admin'},user.cookie)).status).toBe(409);
    expect((await request('/api/administrator/edit',{id:normal.body.user.id,username:'RenamedUser',password:'NewPassword123!'},user.cookie)).status).toBe(200);
    expect((await request('/api/me',undefined,normal.cookie)).body.user).toBeNull();
    expect((await request('/api/login',{username:'RenamedUser',password:'NewPassword123!'})).status).toBe(200);
    expect((await request('/api/login',{username:'NormalUser',password:'CorrectHorseBattery123!'})).status).toBe(401);
    expect((await request('/api/administrator/delete',{id:normal.body.user.id,confirm:'RenamedUser'},user.cookie)).status).toBe(200);
  });
  it('accepts eight-character passwords and rejects shorter passwords', async()=>{
    const {request}=await fixture();
    expect((await request('/api/register',{username:'TooShort',password:'Abc123!'})).status).toBe(400);
    const registered=await request('/api/register',{username:'EightChars',password:'Abc123!?'});
    expect(registered.status).toBe(200);
    expect((await request('/api/login',{username:'EightChars',password:'Abc123!?'})).status).toBe(200);
  });
  it('hands a departing seat to server AI, notifies others and frees their account',async()=>{
    const {service,request,account}=await fixture();const a=await account('Ada'),b=await account('Tunde');
    const created=await request('/api/rooms',{cap:2},a.cookie),code=created.body.room.code;
    await request(`/api/rooms/${code}/join`,{},b.cookie);
    await request(`/api/rooms/${code}/ready`,{ready:true},a.cookie);await request(`/api/rooms/${code}/ready`,{ready:true},b.cookie);
    await request(`/api/rooms/${code}/start`,{},a.cookie);
    const room=JSON.parse((await service.db.prepare('SELECT payload FROM rooms WHERE code=?').get(code))!.payload as string);
    room.game.current=0;room.game.phase='roll';
    await service.db.prepare('UPDATE rooms SET payload=? WHERE code=?').run(JSON.stringify(room),code);
    expect((await request(`/api/rooms/${code}/leave`,{},a.cookie)).status).toBe(200);
    const remaining=(await request(`/api/rooms/${code}`,undefined,b.cookie)).body.room;
    expect(remaining.game.aiPlayers??[]).toEqual([]);expect(remaining.host).toBe(b.body.user.id);
    expect(remaining.game.onlineDepartures[0].returnBy).toBeGreaterThan(Date.now()+8000);
    expect(remaining.game.logs.some((l:{text:string})=>l.text.includes('Ada left the game'))).toBe(true);
    expect((await request('/api/rooms/mine',undefined,a.cookie)).body.room).toBeNull();
    expect((await request(`/api/rooms/${code}/action`,{revision:remaining.revision,action:{type:'roll'}},a.cookie)).status).toBe(403);
    const rejoined=await request(`/api/rooms/${code}/join`,{},a.cookie);expect(rejoined.status).toBe(200);
    expect(rejoined.body.room.game.onlineDepartures).toEqual([]);
    await request(`/api/rooms/${code}/leave`,{},a.cookie);
    const pending=JSON.parse((await service.db.prepare('SELECT payload FROM rooms WHERE code=?').get(code))!.payload as string);
    pending.members[0].returnBy=Date.now()-1;
    await service.db.prepare('UPDATE rooms SET payload=? WHERE code=?').run(JSON.stringify(pending),code);
    await new Promise(resolve=>setTimeout(resolve,750));
    const takenOver=(await request(`/api/rooms/${code}`,undefined,b.cookie)).body.room;
    expect(takenOver.game.aiPlayers).toContain(0);
    expect(takenOver.game.logs.some((l:{text:string})=>l.text.includes('computer has taken over'))).toBe(true);
    expect((await request(`/api/rooms/${code}/join`,{},a.cookie)).status).toBe(409);
    expect((await request(`/api/rooms/${code}`,undefined,b.cookie)).body.room.revision).toBeGreaterThan(remaining.revision);
    expect((await request('/api/rooms',{cap:2},a.cookie)).status).toBe(201);
    await request(`/api/rooms/${code}/leave`,{},b.cookie);
    const empty=JSON.parse((await service.db.prepare('SELECT payload FROM rooms WHERE code=?').get(code))!.payload as string);
    empty.members[1].returnBy=Date.now()-1;await service.db.prepare('UPDATE rooms SET payload=? WHERE code=?').run(JSON.stringify(empty),code);
    await new Promise(resolve=>setTimeout(resolve,750));
    expect(await service.db.prepare('SELECT code FROM rooms WHERE code=?').get(code)).toBeUndefined();
  });
  it('serves the production website and issues secure HTTP-only cookies',async()=>{
    const folder=mkdtempSync(join(tmpdir(),'lag-board-test-'));staticFixtures.push(folder);writeFileSync(join(folder,'index.html'),'<title>MONOPOLY</title>');
    const service=createService({database:':memory:',production:true,origin:'https://game.example',staticDir:folder});services.push(service);
    await new Promise<void>(resolve=>service.server.listen(0,'127.0.0.1',resolve));
    const url=`http://127.0.0.1:${(service.server.address() as AddressInfo).port}`;
    const home=await fetch(url+'/');expect(home.status).toBe(200);expect(await home.text()).toContain('MONOPOLY');
    expect(home.headers.get('content-security-policy')).toContain("script-src 'self'");
    const register=await fetch(url+'/api/register',{method:'POST',headers:{origin:'https://game.example','Content-Type':'application/json'},body:JSON.stringify({username:'ProdUser',password:'CorrectHorseBattery123!'})});
    expect(register.status).toBe(200);expect(register.headers.get('set-cookie')).toContain('__Host-lag-session=');
    expect(register.headers.get('set-cookie')).toContain('HttpOnly');expect(register.headers.get('set-cookie')).toContain('Secure');
  });
  it('persists hashed credentials, remembers sessions, rejects CSRF and revokes logout',async()=>{
    const {service,request,account}=await fixture();const user=await account('Ada');
    expect((await request('/api/me',undefined,user.cookie)).body.user.username).toBe('Ada');
    const stored=(await service.db.prepare('SELECT * FROM users').get())!;
    expect(stored.password).not.toBe('CorrectHorseBattery123!');
    expect((await request('/api/login',{username:'Ada',password:'WrongPassword123!'})).status).toBe(401);
    const login=await request('/api/login',{username:'ada',password:'CorrectHorseBattery123!'});expect(login.status).toBe(200);
    expect((await request('/api/rooms',{cap:4},user.cookie,'https://attacker.example')).status).toBe(403);
    await request('/api/logout',{},user.cookie);expect((await request('/api/me',undefined,user.cookie)).body.user).toBe(null);
    expect((await request('/api/me',undefined,login.cookie)).body.user.username).toBe('Ada');
  });
  it('enforces concurrent room capacity and membership and protects other players moves',async()=>{
    const {request,account}=await fixture();const a=await account('Ada'),b=await account('Tunde'),c=await account('Bisi');
    const created=await request('/api/rooms',{cap:2,public:true},a.cookie),code=created.body.room.code;
    const joins=await Promise.all([request(`/api/rooms/${code}/join`,{},b.cookie),request(`/api/rooms/${code}/join`,{},c.cookie)]);
    expect(joins.map(j=>j.status).sort()).toEqual([200,409]);
    const partner=joins[0].status===200?b:c,outsider=joins[0].status===200?c:b;
    expect((await request(`/api/rooms/${code}`,undefined,outsider.cookie)).status).toBe(403);
    await request(`/api/rooms/${code}/ready`,{ready:true},a.cookie);await request(`/api/rooms/${code}/ready`,{ready:true},partner.cookie);
    const started=await request(`/api/rooms/${code}/start`,{},a.cookie);expect(started.status).toBe(200);
    expect(started.body.room.game.community.every((s:string)=>s.startsWith('CC-hidden'))).toBe(true);
    const room=started.body.room,wrong=room.game.current===0?partner:a,right=room.game.current===0?a:partner;
    expect((await request(`/api/rooms/${code}/action`,{revision:room.revision,action:{type:'roll'}},wrong.cookie)).status).toBe(403);
    const move=await request(`/api/rooms/${code}/action`,{revision:room.revision,action:{type:'roll'}},right.cookie);expect(move.status).toBe(200);
    expect((await request(`/api/rooms/${code}/action`,{revision:room.revision,action:{type:'roll'}},right.cookie)).status).toBe(409);
  });
  it('joins random public rooms but never private rooms and destroys finished rooms',async()=>{
    const {service,request,account}=await fixture();const a=await account('Ada'),b=await account('Tunde');
    const created=await request('/api/rooms',{cap:4,public:false},a.cookie),code=created.body.room.code;
    expect((await request('/api/rooms/random',{},b.cookie)).status).toBe(404);
    await request(`/api/rooms/${code}/join`,{},b.cookie);
    await request(`/api/rooms/${code}/ready`,{ready:true},a.cookie);await request(`/api/rooms/${code}/ready`,{ready:true},b.cookie);
    await request(`/api/rooms/${code}/start`,{},a.cookie);
    const row=(await service.db.prepare('SELECT payload FROM rooms WHERE code=?').get(code))!;
    const room=JSON.parse(row.payload as string),g=room.game;
    g.current=0;g.phase='debt';g.players[0].cash=0;g.payments=[{from:0,to:1,amount:2000000,reason:'Test insolvency'}];
    g.tradeNotifications=[{from:0,to:1,status:'accepted',read:false}];
    await service.db.prepare('UPDATE rooms SET payload=? WHERE code=?').run(JSON.stringify(room),code);
    const end=await request(`/api/rooms/${code}/action`,{revision:room.revision,action:{type:'bankrupt'}},a.cookie);
    expect(end.status).toBe(200);expect(end.body.room.closed).toBe(true);
    expect(await service.db.prepare('SELECT code FROM rooms WHERE code=?').get(code)).toBeUndefined();
    expect((await request(`/api/rooms/${code}`,undefined,b.cookie)).body.room.game.phase).toBe('won');
    const read=await request(`/api/rooms/${code}/action`,{action:{type:'readTradeNotifications',player:0}},a.cookie);
    expect(read.status).toBe(200);expect(read.body.room.game.tradeNotifications[0].readBy).toEqual([0]);
    expect((await request(`/api/rooms/${code}/action`,{action:{type:'readTradeNotifications',player:0}},b.cookie)).status).toBe(403);
  });
});
