import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, CheckCircle2, LogOut, RefreshCw, Search, ShieldCheck, Users } from 'lucide-react';
import { api, type Account } from '../online/api';
import { getBoard } from '../data/boards';
import { compactMoney } from '../game/engine';
import type { GameState } from '../game/types';
import './administrator.css';
import { AdminManagement } from './AdminManagement';
type Room={code:string;host:string;public:boolean;cap:number;updated:number;revision:number;members:(Account&{ready:boolean;left?:boolean;returnBy?:number})[];game:Pick<GameState,'phase'|'turn'|'current'|'players'|'aiPlayers'|'assets'|'logs'>|null};
type Snapshot={generatedAt:number;operator:Account;server:{uptimeSeconds:number;requests:number;failures:number;memoryMB:number;database:string};accounts:(Account&{sessions:number;admin:boolean})[];sessionCount:number;rooms:Room[];completed:{code:string;winner:string;players:string[];updated:number}[]};
export function Administrator(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[login,setLogin]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState<'rooms'|'accounts'|'results'>('rooms'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[tick,setTick]=useState(0);
 useEffect(()=>{let live=true,fetching=false;const refresh=async()=>{if(fetching)return;fetching=true;try{const snapshot=await api<Snapshot>('/administrator');if(live){setData(snapshot);setError('');setLogin(false);}}catch(e){if(live){setError(e instanceof Error?e.message:'Connection unavailable');if(!data){const me=await api<{user:Account|null}>('/me').catch(()=>({user:null}));if(live)setLogin(!me.user);}}}finally{fetching=false;}};void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>{live=false;clearInterval(timer);};},[tick]);
 const room=data?.rooms.find(r=>r.code===selected),board=getBoard('lagos');
 const filter=(text:string)=>text.toLowerCase().includes(query.toLowerCase());
 return <div className="admin-shell"><header className="admin-header"><div><ShieldCheck size={23}/><strong>MONOPOLY <small>LAG-EDITION / ADMINISTRATOR</small></strong></div><nav><a href="/"><ArrowLeft size={16}/>Game</a>{data&&<><span>{data.operator.username}</span><button title="Sign out" aria-label="Sign out" onClick={()=>void api('/logout',{}).then(()=>{setData(null);setTick(t=>t+1);})}><LogOut size={18}/></button></>}</nav></header>
 <main className="admin-main"><div className="admin-heading"><h1>Game operations</h1><span className={error?'admin-offline':'admin-live'}><Activity size={16}/>{error?'Connection needs attention':'Live'}{data&&` · ${new Date(data.generatedAt).toLocaleTimeString()}`}</span><button title="Refresh dashboard" aria-label="Refresh dashboard" onClick={()=>setTick(t=>t+1)}><RefreshCw size={18}/></button></div>
 {error&&<p role="alert" className="admin-error">{error}</p>}
 {data&&!location.pathname.replace(/\/$/,'').endsWith('/create')&&<a href="/administrator/create">Create administrator</a>}
 {!data&&login&&<form className="admin-login" onSubmit={e=>{e.preventDefault();setBusy(true);void api('/login',{username,password}).then(()=>{setPassword('');setTick(t=>t+1);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><h2>Administrator sign in</h2><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?'Signing in...':'Sign in'}</button></form>}
 {data&&!location.pathname.replace(/\/$/,'').endsWith('/create')&&<><section className="admin-metrics">{[['Accounts',data.accounts.length],['Valid sessions',data.sessionCount],['Live games',data.rooms.filter(r=>r.game).length],['Waiting rooms',data.rooms.filter(r=>!r.game).length]].map(([label,value])=><button key={label} onClick={()=>{setTab(label==='Accounts'||label==='Valid sessions'?'accounts':'rooms');setQuery('');setSelected(null);}}><span>{label}</span><strong>{value}</strong></button>)}</section>
 <div className="admin-health"><CheckCircle2 size={16}/>Database: {data.server.database}<span>Uptime: {Math.floor(data.server.uptimeSeconds/60)} min</span><span>Memory: {data.server.memoryMB} MB</span><span>Requests: {data.server.requests}</span><span>Failed requests: {data.server.failures}</span></div>
 <div className="admin-toolbar"><nav>{(['rooms','accounts','results'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setSelected(null);}}>{t==='rooms'?'Rooms':t==='accounts'?'Accounts':'Recent results'}</button>)}</nav><label><Search size={16}/><input aria-label="Search dashboard" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="admin-table-wrap"><table><thead><tr>{(tab==='rooms'?['Room','Host','Visibility','Players','Status','Turn','Updated']:tab==='accounts'?['Username','Account ID','Valid sessions']:['Room','Winner','Players','Finished']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>
 {tab==='rooms'&&data.rooms.filter(r=>filter(r.code+' '+r.host+' '+r.members.map(m=>m.username).join(' '))).map(r=><tr key={r.code}><td><button className="admin-room-link" onClick={()=>setSelected(r.code)}>{r.code}</button></td><td>{r.host}</td><td>{r.public?'Public':'Private'}</td><td>{r.members.length}/{r.cap}</td><td>{r.game?.phase??'Lobby'}</td><td>{r.game?.turn??'-'}</td><td>{new Date(r.updated).toLocaleTimeString()}</td></tr>)}
 {tab==='accounts'&&data.accounts.filter(a=>filter(a.username+' '+a.id)).map(a=><tr key={a.id}><td>{a.username}</td><td><code>{a.id}</code></td><td>{a.sessions}</td></tr>)}
 {tab==='results'&&data.completed.filter(r=>filter(r.code+' '+r.winner)).map(r=><tr key={r.code}><td>{r.code}</td><td>{r.winner}</td><td>{r.players.join(', ')}</td><td>{new Date(r.updated).toLocaleTimeString()}</td></tr>)}
 </tbody></table></div>
 {!(tab==='rooms'?data.rooms:tab==='accounts'?data.accounts:data.completed).length&&<p className="admin-empty">No {tab==='results'?'recent results':tab}.</p>}
 {room&&<section className="admin-room-detail"><h2><Users size={20}/>Room {room.code}<small>Revision {room.revision}</small></h2><div className="admin-table-wrap"><table><thead><tr><th>Player</th><th>Control</th><th>Location</th><th>Cash</th><th>Assets</th></tr></thead><tbody>{room.members.map((m,i)=>{const player=room.game?.players[i];return <tr key={m.id}><td>{m.username}{room.game?.current===i?' · Current turn':''}</td><td>{m.returnBy?`Rejoining · ${Math.max(0,Math.ceil((m.returnBy-data.generatedAt)/1000))}s`:m.left?'Computer':player?.bankrupt?'Bankrupt':m.ready?'Ready':'Human'}</td><td>{player?board.spaces[player.position].name:'Lobby'}</td><td>{player?compactMoney(player.cash):'-'}</td><td>{room.game?Object.values(room.game.assets).filter(a=>a.owner===i).length:0}</td></tr>;})}</tbody></table></div><div className="admin-detail-columns"><div><h3>Asset ownership</h3>{room.game&&Object.entries(room.game.assets).filter(([,a])=>a.owner!==null).map(([id,a])=><p key={id}>{board.spaces[+id].name}<span>{room.game!.players[a.owner!].name} · {a.mortgaged?'Mortgaged':`${a.level} buildings`}</span></p>)}</div><div><h3>Recent activity</h3>{room.game?.logs.map(l=><p key={l.id}>{l.text}</p>)}</div></div></section>}
 </>}
 {data&&(tab==='accounts'||location.pathname.replace(/\/$/,'').endsWith('/create'))&&<AdminManagement accounts={data.accounts} operator={data.operator} refresh={()=>setTick(t=>t+1)}/>}
 </main></div>;
}
