import { useState } from 'react';
import { Pencil, Trash2, UserPlus } from 'lucide-react';
import { api, type Account } from '../online/api';
export function AdminManagement({accounts,operator,refresh}:{accounts:(Account&{admin?:boolean})[];operator:Account;refresh:()=>void}){
 const create=location.pathname.replace(/\/$/,'').endsWith('/create');
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[adminsOnly,setAdminsOnly]=useState(create);
 const [target,setTarget]=useState<Account|null>(null),[confirm,setConfirm]=useState('');
 const [editing,setEditing]=useState<Account|null>(null),[editName,setEditName]=useState(''),[editPassword,setEditPassword]=useState('');
 const run=async(path:string,input:unknown)=>{setBusy(true);setError('');try{await api(path,input);refresh();return true;}catch(e){setError(e instanceof Error?e.message:'Request failed');return false;}finally{setBusy(false);}};
 return <section className="admin-management">{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {create?<><a href="/administrator">Back to dashboard</a><form className="admin-login" onSubmit={e=>{e.preventDefault();void run('/administrator/create',{username,password}).then(ok=>{if(ok){setNotice(`Administrator ${username} created.`);setUsername('');setPassword('');}});}}><h2>Create administrator</h2><label>Username<input required minLength={3} maxLength={20} pattern="[A-Za-z0-9_]+" autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input required type="password" minLength={8} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}><UserPlus size={18}/>Create admin</button></form></>:<a href="/administrator/create"><UserPlus size={16}/>Create admin</a>}
 <div className="admin-account-tools"><h2>Account management</h2><label><input type="checkbox" checked={adminsOnly} onChange={e=>setAdminsOnly(e.target.checked)}/>Administrators only</label></div>
 <div className="admin-table-wrap"><table><thead><tr><th>Username</th><th>Account ID</th><th>Role</th><th>Password</th><th>Actions</th></tr></thead><tbody>{accounts.filter(a=>!adminsOnly||a.admin).map(a=><tr key={a.id}><td>{a.username}{a.id===operator.id?' (you)':''}</td><td><code>{a.id}</code></td><td>{a.admin?'Administrator':'Player'}</td><td>Hashed / reset only</td><td><div className="admin-actions"><button className="admin-delete" title={`Edit ${a.username}`} aria-label={`Edit ${a.username}`} disabled={busy} onClick={()=>{setEditing(a);setEditName(a.username);setEditPassword('');setTarget(null);}}><Pencil size={16}/></button><button className="admin-delete" title={`Delete ${a.username}`} aria-label={`Delete ${a.username}`} disabled={busy||a.id===operator.id} onClick={()=>{setTarget(a);setConfirm('');setEditing(null);}}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>
 {editing&&<form className="admin-login" onSubmit={e=>{e.preventDefault();void run('/administrator/edit',{id:editing.id,username:editName,password:editPassword}).then(ok=>{if(ok){setNotice('Account updated. Password resets sign out existing sessions.');setEditing(null);setEditPassword('');}});}}><h2>Edit {editing.username}</h2><label>Username<input required minLength={3} maxLength={20} pattern="[A-Za-z0-9_]+" value={editName} onChange={e=>setEditName(e.target.value)}/></label><label>New password (leave empty to keep)<input type="password" autoComplete="new-password" minLength={8} maxLength={128} value={editPassword} onChange={e=>setEditPassword(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>{setEditing(null);setEditPassword('');}}>Cancel</button><button className="primary" disabled={busy}>Save changes</button></form>}
 {target&&<form className="admin-delete-confirm" onSubmit={e=>{e.preventDefault();void run('/administrator/delete',{id:target.id,confirm}).then(ok=>{if(ok){setNotice(`${target.username} deleted.`);setTarget(null);}});}}><h3>Delete {target.username}?</h3><p>This permanently removes the account and its sessions. Type the username to confirm.</p><input aria-label="Confirm deletion username" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button type="button" className="secondary" disabled={busy} onClick={()=>setTarget(null)}>Cancel</button><button className="primary" disabled={busy||confirm!==target.username}>Delete account</button></form>}
 </section>;
}
