import { useState } from 'react';
import { Trash2, UserPlus } from 'lucide-react';
import { api, type Account } from '../online/api';
export function AdminManagement({accounts,operator,refresh}:{accounts:(Account&{admin?:boolean})[];operator:Account;refresh:()=>void}){
 const create=location.pathname.replace(/\/$/,'').endsWith('/create');
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[adminsOnly,setAdminsOnly]=useState(true);
 const [target,setTarget]=useState<Account|null>(null),[confirm,setConfirm]=useState('');
 const run=async(path:string,input:unknown)=>{setBusy(true);setError('');try{await api(path,input);refresh();return true;}catch(e){setError(e instanceof Error?e.message:'Request failed');return false;}finally{setBusy(false);}};
 return <section className="admin-management">{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {create?<><a href="/administrator">Back to dashboard</a><form className="admin-login" onSubmit={e=>{e.preventDefault();void run('/administrator/create',{username,password}).then(ok=>{if(ok){setNotice(`Administrator ${username} created.`);setUsername('');setPassword('');}});}}><h2>Create administrator</h2><label>Username<input required minLength={3} maxLength={20} pattern="[A-Za-z0-9_]+" autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input required type="password" minLength={8} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}><UserPlus size={18}/>Create admin</button></form></>:<a href="/administrator/create"><UserPlus size={16}/>Create admin</a>}
 <div className="admin-account-tools"><h2>Account management</h2><label><input type="checkbox" checked={adminsOnly} onChange={e=>setAdminsOnly(e.target.checked)}/>Administrators only</label></div>
 <div className="admin-table-wrap"><table><thead><tr><th>Username</th><th>Role</th><th>Action</th></tr></thead><tbody>{accounts.filter(a=>!adminsOnly||a.admin).map(a=><tr key={a.id}><td>{a.username}{a.id===operator.id?' (you)':''}</td><td>{a.admin?'Administrator':'Player'}</td><td><button className="admin-delete" title={`Delete ${a.username}`} aria-label={`Delete ${a.username}`} disabled={busy||a.id===operator.id} onClick={()=>{setTarget(a);setConfirm('');}}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>
 {target&&<form className="admin-delete-confirm" onSubmit={e=>{e.preventDefault();void run('/administrator/delete',{id:target.id,confirm}).then(ok=>{if(ok){setNotice(`${target.username} deleted.`);setTarget(null);}});}}><h3>Delete {target.username}?</h3><p>This permanently removes the account and its sessions. Type the username to confirm.</p><input aria-label="Confirm deletion username" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button type="button" className="secondary" disabled={busy} onClick={()=>setTarget(null)}>Cancel</button><button className="primary" disabled={busy||confirm!==target.username}>Delete account</button></form>}
 </section>;
}
